### PR TITLE
Update linactuator.scad

### PR DESCRIPTION
**Pull request by 3DSTB**
minor change to prevent error in openSCAD

### CODE REVIEW

**Comment by emard** [comment]
Thanx!

**Comment by 3DSTB** [comment]
You have not merged my commit. Was my change wrong?

**Comment by emard** [comment]
Your change is correct

I clicked  something wrong at github, thought it was green button
now I see change is not accepted hmm

**Comment by emard** [comment]
I applied it manually - check if it works now

**Pull request closed without merging**
